export enum KeyList {
    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',
}

export enum ModifierKeyList {
    CTRL = 'ControlLeft',
    SHIFT = 'ShiftLeft',
    ALT = 'AltLeft',
    CTRL_RIGHT = 'ControlRight',
    SHIFT_RIGHT = 'ShiftRight',
    ALT_RIGHT = 'AltRight',
}
